# Site settings
author: Jeremy Bourne
title: 
header-img: img/home-bg.png
email: jbourne25@yahoo.com
copyright_name: Jeremy Bourne
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jbourne25

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
